package com.collab.common.enums;

public enum NotificationType {
    APPLICATION_RECEIVED,
    APPLICATION_ACCEPTED,
    APPLICATION_REJECTED,
    WORK_SUBMITTED,
    WORK_APPROVED,
    REVISION_REQUESTED,
    TASK_DELETED_BY_ADMIN,
    TASK_VERIFIED,
    NEW_MESSAGE,
    BLOGGER_INVITED,
    REVIEW_RECEIVED,
    TASK_PENDING_REVIEW
}
